name: todolist
description: A simple todo list application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.3.10'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.2.16
  provider: ^6.0.5
  sqflite: ^2.0.3
  flutter_lints: ^2.0.0
  lottie: ^1.4.3
  flutter_slidable: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/launcher_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_logo.png"
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android: true
  ios: true
  web: true
  fullscreen: true

flutter:

  fonts:
    - family: inter
      fonts:
        - asset: fonts/inter_bold.ttf
          weight: 700
        - asset: fonts/inter_medium.ttf
          weight: 500
        - asset: fonts/inter_regular.ttf
          style: normal
    - family: CreateTaskIcon
      fonts:
        - asset: fonts/CreateTaskIcon.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #  - family: Trajan Pro
  #    fonts:
  #      - asset: fonts/TrajanPro.ttf
  #      - asset: fonts/TrajanPro_Bold.ttf
  #        weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
